CVE_2021_44228:
- index: 0
  name: Log4J Attack Vector
  rule_id: '4099843'
  enable: true
  rule: 'SecRule REQUEST_LINE|ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_BODY|REQUEST_HEADERS|XML:/*|XML://@*
    "@rx \${(?:jndi|ctx):" "id:4099843,phase:2,block,t:none,t:lowercase,t:urlDecodeUni,multimatch,msg:''CVE-2021-44228
    / CVE-2021-45046 log4j vulnerability'', tag:''attack-rce'', tag:''paranoia-level/1'',
    severity:''CRITICAL''"

    '
  tags:
  - paranoia-level/1
  - attack-rce
  is_sensitive: false
  mode: "{{ lookup('vars', ENFORCEMENT_MODE) }}"
- index: 1
  name: Log4j Attack ector Evasion Detection
  rule_id: '4099844'
  enable: true
  rule: SecRule REQUEST_LINE|ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_BODY|REQUEST_HEADERS|XML:/*|XML://@*  "@rx
    \${[^}]{0,4}\${" "id:4099844,phase:2,block,t:none,t:lowercase,t:urlDecodeUni,multimatch,msg:'CVE-2021-44228
    / CVE-2021-45046 log4j vulnerability evasion', tag:'attack-rce', tag:'paranoia-level/1',
    severity:'CRITICAL'"
  tags:
  - paranoia-level/1
  - attack-rce
  is_sensitive: false
  mode: "{{ lookup('vars', ENFORCEMENT_MODE) }}"
