avi_cloud_obj:
  api_version: 17.1.2
  name: Default-Cloud
  vtype: CLOUD_VCENTER
  dhcp_enabled: true
  license_type: "LIC_CORES"
  vcenter_configuration:
    username: "root"
    datacenter: "10GTest"
    management_network: "/api/vimgrnwruntime?name=Mgmt_Arista"
    privilege: "WRITE_ACCESS"
    vcenter_url: "10.10.2.10"

cloud_discovery_wait: 5