avi_config:
  tenant:
    - name: TestTenant
  pool:
    - name: app_testtenant-pool
      tenant: TestTenant
      tenant_ref: '/api/tenant?name=TestTenant'
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: "{{ pool_server1 }}"
             type: 'V4'
        - ip:
             addr: "{{ pool_server2 }}"
             type: 'V4'

  vsvip:
    - cloud_ref: /api/cloud?name=Default-Cloud
      east_west_placement: false
      name: vsvip-app_testtenant-Default-Cloud
      tenant: TestTenant
      tenant_ref: '/api/tenant?name=TestTenant'
      vip:
      - auto_allocate_floating_ip: false
        auto_allocate_ip: false
        avi_allocated_fip: false
        avi_allocated_vip: false
        enabled: true
        ip_address:
          addr: "{{ app_test_tenant_vip }}"
          type: V4
        vip_id: '1'
      vrf_context_ref: /api/vrfcontext/?name=global

  virtualservice:
    - name: app_testtenant
      tenant: TestTenant
      tenant_ref: '/api/tenant?name=TestTenant'
      services:
        - port: 80
        - port: 8080
      pool_ref: '/api/pool?name=app_testtenant-pool'
      vsvip_ref: /api/vsvip/?name=vsvip-app_testtenant-Default-Cloud
