- hosts: localhost
  connection: local
  vars_files:
    - "../vars/creds_unsecure.yml"
  vars:
    api_version: 17.1.2
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Avi Cloud | Setup VMWare Cloud with Write Access
      include_role:
        name: cloud
      vars:
        cloud_name: vmware
        site_dir: ../
