#-------------------Avi Controller-----------------------------
#----- Avi controller required information
avi_controller_ip: 
avi_username: 
avi_password: 

#----- Avi controller optional information
tenant:
cloud:
segroup:


#-------------------VMC vCenter-----------------------------
#---- VMC vcenter required information
vcenter_hostname: 
vcenter_username: 
vcenter_password: 

#---- VMC vCenter optional information
datacenter:
cluster:
datastore:
folder:





#-------------------Avi SE-----------------------------
#---- Avi SE required information
management_network_pg: 
data_nic_parking_pg: 

#---- Avi SE mgmt IP information
#---- If blank, DHCP 
#---- mask is in bits; eg 24
se_mgmt_ip:
se_mgmt_mask:
se_mgmt_gw:


#---- Avi SE optional information
ova_path: 



se_memory_mb: 4096
se_memory_reserve_lock: False

se_num_cpus: 2
se_cpu_reserve_mhz:

se_disk_size_gb: 20


#---- Avi SE optional Data NIC information
#---- For nics that have a pg defined but no IP info, DHCP will be used
#---- mask is in bits; eg 24


data_network1:
  se_int_pg: 
  se_int_ip:
  se_int_mask:

data_network2:
  se_int_pg:
  se_int_ip:
  se_int_mask:

data_network3:  
  se_int_pg:
  se_int_ip:
  se_int_mask:
  
data_network4:
  se_int_pg:
  se_int_ip:
  se_int_mask:
  
data_network5:  
  se_int_pg:
  se_int_ip:
  se_int_mask:
  
data_network6:
  se_int_pg:
  se_int_ip:
  se_int_mask:
  
data_network7:
  se_int_pg:
  se_int_ip:
  se_int_mask:
  
data_network8:
  se_int_pg:
  se_int_ip:
  se_int_mask:
  
data_network9:
  se_int_pg:
  se_int_ip:
  se_int_mask:



