avi_config:
  pool:
    - name: app1-pool
      lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
      servers:
        - ip:
             addr: '10.90.64.16'
             type: 'V4'
        - ip:
             addr: '10.90.64.14'
             type: 'V4'

  virtualservice:
    - name: app1
      services:
        - port: 80
      pool_ref: '/api/pool?name=app1-pool'
      vip:
        - ip_address:
            addr: 10.90.64.240
            type: 'V4'
          vip_id: '1'


avi_pool_objs:
  - name: app1-pool
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    servers:
      - ip:
           addr: '10.90.64.16'
           type: 'V4'
      - ip:
           addr: '10.90.64.14'
           type: 'V4'

avi_virtualservice_objs:
  - name: app1
    services:
      - port: 80
    pool_ref: '/api/pool?name=app1-pool'
    vip:
      - ip_address:
          addr: 10.90.64.240
          type: 'V4'
        vip_id: '1'
