---
# When running on Ubuntu 16.04.2 you will need to change python to python3
# ansible-playbook -i 10.70.160.51, docker.yml -u ubuntu --ask-pass -e 'ansible_python_interpreter=/usr/bin/python3' --ask-become-pass
- hosts: all
  become: yes
  pre_tasks:
    - name: Enable ipv4 forwarding
      sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
  roles:
    - role: avinetworks.docker
      docker_edition: ce
      docker_storage_driver: aufs
      docker_live_restore: true
    - role: avinetworks.avicontroller
      con_version: 17.1.2-9038-20170607.005544
      con_disk_gb: 50
