#----------Controllers to Poll Data From - REQUIRED ------------
#---------------------------------------------------------------
controllers:
   - avi_cluster_name: demo_controller1
     avi_controller: 169.254.0.1
     avi_user: admin
     #comment: ACCEPTS PLAIN TEXT OR BASE64 ENCODED PASSWORD
     avi_pass: password
     tags:
      environment: dev
      location: datacenter1      
     #comment: Realtime metrics will cause the script to take longer to complete, optional
     virtualservice_stats_config:
         virtualservice_metrics: True
         virtualservice_realtime: False
         virtualservice_runtime: False
         virtualservice_metrics_list:
            - l4_client.avg_bandwidth
            - l4_client.avg_rx_pkts
            - l4_client.avg_tx_pkts
            - l4_client.avg_rx_bytes
            - l4_client.avg_tx_bytes
            - l7_client.avg_ssl_handshakes_new
     serviceengine_stats_config:
         serviceengine_metrics: True
         serviceengine_runtime: True
         serviceengine_realtime: True
     pool_stats_config:
         pool_metrics: False
         pool_runtime: True
         pool_realtime: False
     controller_stats_config:
         controller_metrics: True
         controller_runtime: True
         controller_metrics_list:
            - controller_stats.avg_cpu_usage
            - controller_stats.avg_disk_usage
            - controller_stats.avg_mem_usage
     metrics_endpoint_config:
         - type: influxdb
           enable: True
           server: 169.254.0.1
           server_port: 8086
           protocol: http
           db: avi
           #_comment":"Change metric_prefix only if you need to define a prefix",
           metric_prefix: ""
           #_comment":"If using auth on influxdb set auth-enabled to true and modify the credential values",
           auth-enabled: False
           username: admin
           password: password
         - type: wavefront
           enable: True
           instance: x.x.x.x.x.wavefront.com
           api_key: 12a345bc-de6f-789a-0bcd-ef1234a5bcd6



   - avi_cluster_name: demo_controller2
     avi_controller: 169.254.0.2
     avi_user: admin
     #comment: ACCEPTS PLAIN TEXT OR BASE64 ENCODED PASSWORD
     avi_pass: password
     #comment: Realtime metrics will cause the script to take longer to complete, optional
     virtualservice_stats_config:
         virtualservice_metrics: True
         virtualservice_realtime: False
         virtualservice_runtime: False
         virtualservice_metrics_list:
     serviceengine_stats_config:
         serviceengine_metrics: False
         serviceengine_runtime: False
         serviceengine_realtime: False
     pool_stats_config:
         pool_metrics: False
         pool_runtime: False
         pool_realtime: False
     controller_stats_config:
         controller_metrics: True
         controller_runtime: True
     metrics_endpoint_config:
         - type: elasticsearch
           enable: True
           server: 169.254.0.1
           server_port: 9200
           protocol : https
           index: avimetrics
           #_comment:default time filter field name,
           timestamp: "@timestamp"
           #_comment:If using auth on elasticsearch set auth-enabled to true and modify the credential values
           auth-enabled: False
           username: admin
           password: password
         - type: datadog
           enable: False
           api_url: app.datadoghq.com/api/v1/series?api_key=
           api_key: abcdefghijgklmnopqrstuvwxyz12345
                      
             
             



##----------Metrics Endpoint EXAMPLES for metric_endpoint_config ------------
##------------------------------------------------
#
#
##----------appdynamics------------
#  - type: appdynamics_http
#    enable: False
#    server: 169.254.0.1
#    server_port: 8293
#
#
#
##----------datadog------------
#  - type: datadog
#    enable: False
#    api_url: app.datadoghq.com/api/v1/series?api_key=
#    api_key: abcdefghijgklmnopqrstuvwxyz12345
#
#
#
##----------elasticsearch------------
#  - type: elasticsearch
#    enable: False
#    server: 169.254.0.1
#    server_port: 9200
#    protocol : https
#    index: avimetrics
#    #_comment:default time filter field name,
#    timestamp: "@timestamp"
#    #_comment:If using auth on elasticsearch set auth-enabled to true and modify the credential values
#    auth-enabled: True
#    username: admin
#    password: password
#
#
#
##----------graphite------------
#  - type: graphite
#    enable: False
#    server: 169.254.0.1
#    server_port: 2003
#
#
#
##----------influxdb------------
#  - type: influxdb
#    enable: False
#    server: 169.254.0.1
#    server_port: 8086
#    protocol: https
#    db: avi
#    #_comment":"Change metric_prefix only if you need to define a prefix",
#    metric_prefix: ""
#    #_comment":"If using auth on influxdb set auth-enabled to true and modify the credential values",
#    auth-enabled: False
#    username: admin
#    password: password
#
#
#
##----------logstash------------
#  - type: logstash
#    enable: False
#    #_comment": "logstash codec => json_lines"
#    server: 169.254.0.1
#    server_port: 517
#    #_comment": "tcp or udp"
#    protocol: udp
#
#
#
##----------splunk hec------------
#  - type: splunk
#    enable: False
#    server: 169.254.0.1
#    #_comment:"HEC_PROTOCOL OPTIONS ARE HTTP OR HTTPS",
#    hec_protocol: https
#    hec_port: 8088
#    hec_token: abcdefgh-ijkl-mnop-qrst-uvwxyz123456
#    #_comment":"INDEX TYPE EVENT OR METRIC"
#    index_type: event
#    index: avi:metrics
#
#
#
##----------wavefront------------
#  - type: wavefront
#    enable: False
#    instance: xxxxxxxx.wavefront.com
#    #_comment:  If using direct ingestion specify an api_key, if no key then wavefront proxy will be used
#    #api_key: 12a345bc-de6f-789a-0bcd-ef1234a5bcd6
#    #_comment:  If using proxy specify the listening port, if not defined defaults to 2878
#    proxy_port: 2878
#
#
#
